* Fallback looking for syslinux/silo/yaboot in $CODENAME when $DI_CODENAME   didn't gave any result. This is useful when using partial mirrors built by   simple-cdd while trying to build a Debian CD using a newer d-i (in my case   etch CD with lenny d-i). * Use dpkg --fsys-tarfile instead of ar for extracting files from deb   packages. The previous invocation could have failed for packages using   something other than gzip compression.

diff --git a/tools/boot/lenny/boot-powerpc b/tools/boot/lenny/boot-powerpc
--- a/tools/boot/lenny/boot-powerpc
+++ b/tools/boot/lenny/boot-powerpc
@@ -55,14 +55,18 @@ add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-hfs-volid Debian/PowerPC_${CODENAME}
 cd $INSTALLDIR
 # Extract yaboot from the archive
 if [ -z "$YABOOT_DEBUG" ]; then
-    YADEB=`$BASEDIR/tools/which_deb $MIRROR $DI_CODENAME yaboot`
-    (ar p "$MIRROR/${YADEB}" data.tar.gz | \
-	tar zxf - -C . ./usr/lib/yaboot/yaboot)
+    YADEB=$(find_pkg_file yaboot)
+    if [ -z "$YADEB" ]; then
+        echo "ERROR: the yaboot package is required." >&2
+        exit 1
+    fi
+    (dpkg --fsys-tarfile "$MIRROR/$YADEB" | \
+	tar xf - -C . ./usr/lib/yaboot/yaboot)
     mv usr/lib/yaboot/yaboot .
     rm -rf usr
 
     echo $YADEB >> $CDDIR/../$N.pkgs_extracted
-    $BASEDIR/tools/which_deb $MIRROR $DI_CODENAME yaboot source >> $CDDIR/../$N.pkgs_extracted
+    find_pkg_file yaboot source >> $CDDIR/../$N.pkgs_extracted
 
 else
  cp -f $YABOOT_DEBUG yaboot
diff --git a/tools/boot/lenny/boot-sparc b/tools/boot/lenny/boot-sparc
--- a/tools/boot/lenny/boot-sparc
+++ b/tools/boot/lenny/boot-sparc
@@ -38,13 +38,17 @@ cd $CDDIR/..
 # Setup directories
 mkdir -p $inst/boot
 
-silo_deb=`$BASEDIR/tools/which_deb $MIRROR $DI_CODENAME silo`
+silo_deb=$(find_pkg_file silo)
+if [ -z "$silo_deb" ]; then
+       echo "ERROR: silo package is required"
+       exit 1
+fi 
 # put the relevant parts of SILO boot loader
-(ar p $MIRROR/$silo_deb data.tar.gz | \
-	tar zxf - -C $inst/ ./boot/{isofs,second}.b)
+(dpkg --fsys-tarfile $MIRROR/$silo_deb | \
+	tar xf - -C $inst/ ./boot/{isofs,second}.b)
 
 echo $silo_deb >> $CDDIR/../$N.pkgs_extracted
-$BASEDIR/tools/which_deb $MIRROR $DI_CODENAME silo source >> $CDDIR/../$N.pkgs_extracted
+find_pkg_file silo source >> $CDDIR/../$N.pkgs_extracted
 
 # Some custom etc files
 cp -f -p $BASEDIR/data/lenny/sparc/silo.conf $inst/boot/
diff --git a/tools/boot/lenny/boot-x86 b/tools/boot/lenny/boot-x86
--- a/tools/boot/lenny/boot-x86
+++ b/tools/boot/lenny/boot-x86
@@ -174,12 +174,16 @@ if [ "$THISTYPE" = "isolinux" ]; then
 	cp -lf cdrom/initrd.gz $CDDIR/$INSTALLDIR/
 
 	mkdir -p $CDDIR/../syslinux
-	SYSLINUXDEB=`$BASEDIR/tools/which_deb $MIRROR $DI_CODENAME syslinux`
-	(ar p "$MIRROR/${SYSLINUXDEB}" data.tar.gz | \
-		tar zxf - -C $CDDIR/../syslinux ./usr/lib)
+	SYSLINUXDEB=$(find_pkg_file syslinux)
+	if [ -z "$SYSLINUXDEB" ]; then
+		echo "ERROR: syslinux package is required" >&2
+		exit 1
+	fi
+	(dpkg --fsys-tarfile "$MIRROR/$SYSLINUXDEB" | \
+		tar xf - -C $CDDIR/../syslinux ./usr/lib)
 
 	echo $SYSLINUXDEB >> $CDDIR/../$N.pkgs_extracted
-	$BASEDIR/tools/which_deb $MIRROR $DI_CODENAME syslinux source >> $CDDIR/../$N.pkgs_extracted
+	find_pkg_file syslinux source >> $CDDIR/../$N.pkgs_extracted
 
 	add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
 	add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
