Switch bootloader from elilo to grub-efi-ia64 on ia64

diff --git a/tools/boot/buster/boot-ia64 b/tools/boot/buster/boot-ia64
--- a/tools/boot/buster/boot-ia64
+++ b/tools/boot/buster/boot-ia64
@@ -1,6 +1,9 @@
 #!/bin/bash
+
+# Based on boot-arm64
 #
-# boot-ia64
+# Do install stuff for ia64, including making bootable CDs
+# Works with debian-installer
 #
 # $1 is the CD number
 # $2 is the temporary CD build dir
@@ -8,6 +11,10 @@
 . $BASEDIR/tools/boot/$DI_CODENAME/common.sh
 
 set -e
+#set -x
+
+# Workaround for #823881:
+export MTOOLS_SKIP_CHECK=1
 
 N=$1
 CDDIR=$2
@@ -30,33 +37,98 @@ else
     DI_WWW_HOME=$(echo $DI_WWW_HOME | sed "s,%ARCH%,$ARCH,")
 fi
 
+case "$MKISOFS" in
+    *xorriso*)
+        XORRISO_VER=$(xorriso_version)
+        ;;
+    *)
+        echo "ERROR: debian-cd depends on xorriso for making $ARCH bootable CDs."
+        exit 1;
+        ;;
+esac
+
 cd $CDDIR/..
 
-# Download boot images
-for image in boot.img; do
+BOOT_IMAGES="cdrom/initrd.gz cdrom/vmlinuz cdrom/debian-cd_info.tar.gz"
+
+# Download boot images.
+for image in $BOOT_IMAGES; do
     if [ ! -e "$image" ]; then
-	if [ ! "$DI_WWW_HOME" ];then
-        	if [ ! "$DI_DIR" ];then
-		   DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images"
-		fi
-		cp "$DI_DIR/cdrom/$image" . || \
-		cp "$DI_DIR/$image" .
-	else
-		$WGET "$DI_WWW_HOME/cdrom/$image" || \
-		$WGET "$DI_WWW_HOME/$image"
-	fi
+        dir=$(dirname $image)
+        mkdir -p $dir
+        if [ -n "$LOCAL"  -a -f "${LOCALDEBS:-$MIRROR}/dists/$DI_DIST/local/installer-$ARCH/current/images/$image" ]; then
+            cp "${LOCALDEBS:-$MIRROR}/dists/$DI_DIST/local/installer-$ARCH/current/images/$image" "$image"
+        elif [ ! "$DI_WWW_HOME" ];then
+            if [ ! "$DI_DIR" ];then
+                DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images"
+            fi
+            cp "$DI_DIR/$image" "$image"
+        else
+            $WGET "$DI_WWW_HOME/$image" -O "$image"
+        fi
     fi
 done
 
-mkdir -p boot$N/boot
-cp -f boot.img boot$N/boot/
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-no-emul-boot"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-b boot/boot.img"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-c boot/boot.catalog"
+mkdir -p $CDDIR/$INSTALLDIR
+cp -lf cdrom/vmlinuz $CDDIR/$INSTALLDIR/
+cp -lf cdrom/initrd.gz $CDDIR/$INSTALLDIR/
 
-bls=$(calc_boot_size "boot$N/boot/boot.img")
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-boot-load-size $bls"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_dirs "boot$N"
+# Boot setup including config and help files comes from d-i.
+mkdir -pv $PWD/boot$N
+cat cdrom/debian-cd_info.tar.gz | (cd boot$N/; tar zx)
 
-# done
+if [ -d boot$N/grub ] ; then
+    echo "  Adding EFI boot code for $ARCH on CD$N"
 
+    # Move GRUB files to the right place.
+    mkdir -p $CDDIR/EFI/boot
+    mcopy -n -s -i boot$N/grub/efi.img '::efi/*' $CDDIR/EFI
+    mkdir -p $CDDIR/boot/grub
+    mv boot$N/grub/* $CDDIR/boot/grub/
+    rmdir boot$N/grub
+
+    # Stuff the EFI boot files into a FAT filesystem, making it as
+    # small as possible. We end up re-packing like this in case we're
+    # making a multi-arch image
+
+    # First, work out how many blocks we need
+    blocks=$(calculate_efi_image_size $CDDIR)
+
+    # Now make a new image to contain the files
+    rm -f $CDDIR/boot/grub/efi.img
+    mkfs.msdos -v -C "$CDDIR/boot/grub/efi.img" $blocks >/dev/null
+
+    # And copy them into place
+    mmd -i "$CDDIR/boot/grub/efi.img" ::efi
+    mcopy -o -s -i "$CDDIR/boot/grub/efi.img" $CDDIR/EFI/* \
+        "::efi"
+
+    # Ugh - different code here depending on the version of xorriso we've got
+    if [ $XORRISO_VER -le 10202 ] ; then
+        echo "ERROR: debian-cd depends on xorriso > 1.2.2 for making $ARCH bootable CDs."
+        exit 1;
+    elif [ $XORRISO_VER -gt 10202 ] ; then
+        echo "    Using newer EFI support in xorriso $XORRISO_VER"
+
+	# Location of the EFI boot image, and don't emulate a floppy or HD
+        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-e boot/grub/efi.img -no-emul-boot"
+
+	# Add an *extra* partition on the end for the EFI bits
+	add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-append_partition 2 0xef $CDDIR/boot/grub/efi.img"
+
+	# And force alignment
+	add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-partition_cyl_align all"
+    fi
+
+    # Finally, belt and braces - fix up the %install% entries in grub
+    # in case they're still there
+    sed -i "s,\%install\%,$INSTALLDIR,g" $CDDIR/boot/grub/grub.cfg
+
+    # Substitute custom KERNEL_PARAMS into grub.cfg
+    sed -i "s,/vmlinuz ,/vmlinuz $KERNEL_PARAMS ,g" $CDDIR/boot/grub/grub.cfg
+
+else
+    echo "  No EFI boot code for $ARCH on CD$N"
+fi
+
+# th,th, thats all
