Add m68k reorg support

diff --git a/tools/boot/sarge/boot-m68k b/tools/boot/sarge/boot-m68k
--- a/tools/boot/sarge/boot-m68k
+++ b/tools/boot/sarge/boot-m68k
@@ -15,18 +15,19 @@ CDDIR=$2
 INSTALLDIR=$CDDIR/install
 
 # the ! case further down doesn't seem to work.
-if [ ! "$DI_WWW_HOME" ];then
-	DI_WWW_HOME="default" 
-fi
+#if [ ! "$DI_WWW_HOME" ];then
+#	DI_WWW_HOME="default" 
+#fi
 if [ "$DI_WWW_HOME" = "default" ];then
-   DI_WWW_HOME="http://people.debian.org/~smarenka/d-i/images-m68k/daily"
+   DI_WWW_HOME="http://people.debian.org/~smarenka/d-i/images-m68k/daily/"
 elif [ "$DI_WWW_HOME" = "test" ];then
-   DI_WWW_HOME="http://people.debian.org/~smarenka/d-i/test/cd"
+   DI_WWW_HOME="http://people.debian.org/~smarenka/d-i/test/cd/"
 fi
 if [ ! "$DI_DIST" ]; then
    DI_DIST="$DI_CODENAME"
 fi
 
+DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images"
 DI_BOOTLOADER="http://people.debian.org/~smarenka/d-i"
 
 cd $CDDIR/..
@@ -41,6 +42,7 @@ fi
 
 echo "DI_WWW_HOME: $DI_WWW_HOME"
 echo "DI_BOOTLOADER: $DI_BOOTLOADER"
+echo "DI_DIR: $DI_DIR"
 
 install_languages $CDDIR
 
@@ -54,43 +56,53 @@ cd $INSTALLDIR
 # available to build the cd.
 
 if [ ! "$DI_WWW_HOME" ];then
-	DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images"
-	SUBARCHS=`find "$DI_DIR/*" -type d -print | sed -e 's,.*/,,'`
-
-	for subarch in $SUBARCHS; do
-		echo "subarch: $subarch"
-		mkdir $subarch
-		cp -a "$DI_DIR"/$subarch/* $subarch
-	done
-	cp "$DI_DIR/cdrom-initrd.gz" root.bin
-	if [ -f "$DI_DIR/cdrom22-initrd.gz" ]; then 
-		cp "$DI_DIR/cdrom22-initrd.gz" root22.bin
+	if [ ! $DI_DIR ]; then
+		echo "Rats, can't find: $DI_DIR!"
 	fi
-	cp "$DI_DIR/MANIFEST" .
+	cp -a $DI_DIR/* .
+
+#	SUBARCHS=`find "$DI_DIR/*" -type d -print | sed -e 's,.*/,,'`
+#	for subarch in $SUBARCHS; do
+#		echo "subarch: $subarch"
+#		mkdir $subarch
+#		cp -a "$DI_DIR"/$subarch/* $subarch
+#	done
+#	cp "$DI_DIR/cdrom-initrd.gz" root.bin
+#	if [ -f "$DI_DIR/cdrom22-initrd.gz" ]; then 
+#		cp "$DI_DIR/cdrom22-initrd.gz" root22.bin
+#	fi
+#	cp "$DI_DIR/MANIFEST" .
 else
-	SUBARCHS=$(wget -q "$DI_WWW_HOME/" -O - | \
-		sed -n -e 's/.*>\(.*\)\/<.*/\1/p')
+	wget -q -np -nH --cut-dirs=4 -r -l 3 -R '.gif,.log,stats.txt,index*' "$DI_WWW_HOME"
 
-	for subarch in $SUBARCHS; do
-		echo "subarch: $subarch"
-		mkdir $subarch
-		cd $subarch
-		wget -q -np -nd -r -l 1 -R '.gif' "$DI_WWW_HOME/$subarch"
-		rm index*
-		cd ..
-	done
-	wget -O root.bin "$DI_WWW_HOME/cdrom-initrd.gz"
-	if ! wget -O root22.bin "$DI_WWW_HOME/cdrom22-initrd.gz" ; then
-		rm root22.bin
-	fi
-	wget -O MANIFEST "$DI_WWW_HOME/MANIFEST"
+#	SUBARCHS=$(wget -q "$DI_WWW_HOME/" -O - | \
+#		sed -n -e 's/.*>\(.*\)\/<.*/\1/p')
+
+#	for subarch in $SUBARCHS; do
+#		echo "subarch: $subarch"
+#		mkdir $subarch
+#		cd $subarch
+#		wget -q -np -nd -r -l 1 -R '.gif' "$DI_WWW_HOME/$subarch"
+#		rm index*
+#		cd ..
+#	done
+#	wget -O root.bin "$DI_WWW_HOME/cdrom-initrd.gz"
+#	if ! wget -O root22.bin "$DI_WWW_HOME/cdrom22-initrd.gz" ; then
+#		rm root22.bin
+#	fi
+#	wget -O MANIFEST "$DI_WWW_HOME/MANIFEST"
+
 fi
 
+SUBARCHS=`grep vmlinu MANIFEST | cut -d'-' -f3 | sort -u | awk '{printf "%s ", $1}'`
 # grab unpackged stuff
+if [ -d tools ]; then
+	cd tools
+fi
 for subarch in $SUBARCHS; do
 	TARF="bootloaders-$subarch.tar.bz2"
-	if `wget -O $TARF "$DI_BOOTLOADER/$TARF"` ; then
-		tar -xvjf $TARF
+	if `wget -q -O $TARF "$DI_BOOTLOADER/$TARF"` ; then
+		tar -xjf $TARF
 	fi
 	rm -f $TARF
 done
@@ -104,13 +116,22 @@ if [ "" != "`echo $SUBARCHS | grep amiga`" ]; then
 
 	# Setup amiga icons
 	cp amiga/amiga.info  $CDDIR/install.info
+	if [ -d $INSTALLDIR/tools ]; then
+		cp amiga/amiga.info  $INSTALLDIR/tools.info
+	fi
 	mv amiga/amiga.info  .
 fi
+
+cd $INSTALLDIR
 
 # bvme6000 specific stuff
 if [ "" != "`echo $SUBARCHS | grep bvme6000`" ]; then
 	mkdir -p $CDDIR/boot1/boot
-	cp bvme6000/cdrom-boot.img.gz $CDDIR/boot1/boot/boot.bin
+	if [ -f bvme6000/cdrom-boot.img.gz ]; then
+		cp bvme6000/cdrom-boot.img.gz $CDDIR/boot1/boot/boot.bin
+	else
+		cp cdrom/bvme6000-boot.img.gz $CDDIR/boot1/boot/boot.bin
+	fi
 	echo -n " -b boot/boot.bin -c boot/boot.catalog boot1" \
     	>> $N.mkisofs_opts
 fi
