Make kfreebsd & hurd images usbkey-bootable. Closes: #739422
debian-installer now has extra steps to create a grub_embed file which
can be passed to xorriso's --embedded-boot option. Add corresponding
code in debian-cd to use it to make images USB bootable.

Patch from Samuel Thibault.

diff --git a/tools/boot/jessie/boot-kfreebsd b/tools/boot/jessie/boot-kfreebsd
--- a/tools/boot/jessie/boot-kfreebsd
+++ b/tools/boot/jessie/boot-kfreebsd
@@ -27,6 +27,21 @@ if [ "$DI_WWW_HOME" = "default" ];then
     try_di_image_cache
 fi
 
+case "$MKISOFS" in
+    *xorriso*)
+        XORRISO_VER=$($MKISOFS --version 2>&1 | awk '
+            NR==1 {
+                 split($3, ver, ".")
+                 print ver[1]*10000+ver[2]*100+ver[3]
+            }')
+        # OK
+        ;;
+    *)
+	echo "ERROR: debian-cd now depends on xorriso for making x86 bootable CDs."
+	exit 1;
+	;;
+esac
+
 cd $CDDIR/..
 
 # Only disc 1 bootable
@@ -74,6 +89,7 @@ mkdir -p boot$N
 tar -C boot$N -zxf cdrom/debian-cd_info.tar.gz
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-b boot/grub/grub_eltorito"
+[ -f boot$N/boot/grub/grub_embed ] && add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "--embedded-boot boot$N/boot/grub/grub_embed"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-c boot/boot.cat"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-no-emul-boot"
 
