Refactor boot scripts
Move sourced/shared scripts to boot-*-common
Rearrange common definitions in each boot script to make them more
similar
Add common support for %ARCH% substitutions in DI_WWW_HOME
Fix boot-alpha to use which_deb when looking for aboot
Merge mips* together, using boot-mips-common

diff --git a/tools/boot/stretch/boot-alpha b/tools/boot/stretch/boot-alpha
--- a/tools/boot/stretch/boot-alpha
+++ b/tools/boot/stretch/boot-alpha
@@ -24,10 +24,23 @@ set -e
 
 N=$1
 CDDIR=$2
-BOOTDIR=
-if [ "$DI_WWW_HOME" = "default" ];then
+INSTALLDIR="install"
+
+# Common options for all disks
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-l"
+
+# Exit if this is not CD#1/DVD#1
+if [ $N != "1" ]; then
+    exit 0
+fi
+
+if [ "$DI_WWW_HOME" = "default" ]; then
     DI_WWW_HOME="https://d-i.debian.org/daily-images/alpha/daily/cdrom/"
     try_di_image_cache
+else
+    DI_WWW_HOME=$(echo $DI_WWW_HOME | sed "s,%ARCH%,$ARCH,")
 fi
 
 cd $CDDIR/..
@@ -36,19 +49,19 @@ cd $CDDIR/..
 # This script is called with $1 (now $N) as the CD to 
 # make bootable.
 
-# Common options for all disks
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-l"
-
 # Only disk 1* bootable
 if [ $N != 1 ]; then
 	exit 0
 fi
 
+ABOOTDEB=$(find_pkg_file aboot-base)
+if [ -z "$ABOOTDEB" ] ; then 
+    echo "ERROR:  the aboot-base package is required." >&2
+    exit 1
+fi
+
 mkdir boot$N
-ab_deb=`ls $MIRROR/pool/main/a/aboot/aboot-base_*.deb | tail -1`
-(dpkg --fsys-tarfile "$ab_deb" | tar xf - -C boot$N/ ./boot/bootlx)
+(dpkg --fsys-tarfile "$MIRROR/$ABOOTDEB" | tar xf - -C boot$N/ ./boot/bootlx)
 
 # Download boot images
 # XXX: Driver floppies?  Any alpha that /has/ a CDROM should be able to
diff --git a/tools/boot/stretch/boot-kfreebsd-common b/tools/boot/stretch/boot-kfreebsd-common
--- a/tools/boot/stretch/boot-kfreebsd-common
+++ b/tools/boot/stretch/boot-kfreebsd-common
@@ -14,17 +14,33 @@ set -e
 
 N=$1
 CDDIR=$2
-BOOTDIR=
-if [ "$DI_WWW_HOME" = "default" ];then
+INSTALLDIR="install"
+
+# Common options for all disks
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-l"
+
+# Exit if this is not CD#1/DVD#1
+if [ $N != "1" ]; then
+    exit 0
+fi
+
+if [ "$DI_WWW_HOME" = "default" ]; then
     # Tempting as it might be to merge these two definitions using $ARCH,
     # do *not* do that - these defs are parsed out by other scripts that
     # won't cope with that
     if [ "$ARCH" = kfreebsd-i386 ]; then
         DI_WWW_HOME="https://d-i.debian.org/daily-images/kfreebsd-i386/daily/"
-    else
+    elif [ "$ARCH" = kfreebsd-amd64 ]; then
         DI_WWW_HOME="https://d-i.debian.org/daily-images/kfreebsd-amd64/daily/"
+    else
+        echo "$0: unknown arch $ARCH; abort"
+	exit 1
     fi
     try_di_image_cache
+else
+    DI_WWW_HOME=$(echo $DI_WWW_HOME | sed "s,%ARCH%,$ARCH,")
 fi
 
 case "$MKISOFS" in
@@ -38,12 +54,6 @@ case "$MKISOFS" in
 esac
 
 cd $CDDIR/..
-
-# Only disc 1 bootable
-if [ $N != 1 ]; then
-       add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
-       exit 0
-fi
 
 # Download boot images.
 BOOT_IMAGES="cdrom/debian-cd_info.tar.gz cdrom/kfreebsd-10.gz cdrom/initrd.gz"
@@ -82,7 +92,6 @@ fi
 # Install bootloader
 mkdir -p boot$N
 tar -C boot$N -zxf cdrom/debian-cd_info.tar.gz
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-b boot/grub/grub_eltorito"
 [ -f boot$N/boot/grub/grub_embed ] && add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "--embedded-boot boot$N/boot/grub/grub_embed"
 add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-c boot/boot.cat"
diff --git a/tools/boot/stretch/boot-s390x b/tools/boot/stretch/boot-s390x
--- a/tools/boot/stretch/boot-s390x
+++ b/tools/boot/stretch/boot-s390x
@@ -23,23 +23,32 @@ set -e
 
 N=$1
 CDDIR=$2
+INSTALLDIR="install"
 
-cd $CDDIR/..
-
-if [ $N != "1" ] ; then
+# Exit if this is not CD#1/DVD#1
+if [ $N != "1" ]; then
     add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
+    add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
+    add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-l"
     exit 0
 fi
 
-if [ "$DI_WWW_HOME" = "default" ];then
-    # Tempting as it might be to merge these two definitions using $ARCH,
-    # do *not* do that - these defs are parsed out by other scripts that
-    # won't cope with that
+if [ "$DI_WWW_HOME" = "default" ]; then
+    # Tempting as it might be to merge these definitions using $ARCH,
+    # do *not* do that - these defs are parsed out by other scripts
+    # that won't cope with that
     if [ "$ARCH" = s390x ]; then
         DI_WWW_HOME="https://d-i.debian.org/daily-images/s390x/daily"
+    else
+        echo "$0: unknown arch $ARCH; abort"
+	exit 1
     fi
     try_di_image_cache
+else
+    DI_WWW_HOME=$(echo $DI_WWW_HOME | sed "s,%ARCH%,$ARCH,")
 fi
+
+cd $CDDIR/..
 
 imagedir="boot$N/boot"
 mkdir -p $imagedir
