* Added tools/pi-makelist this time. * Removed set -e from tools/apt-selection. Apt must be able to fail ... * Added a separate pi-makelist target. * Updated the README with Pseudo Image Kit information.

diff --git a/tools/apt-selection b/tools/apt-selection
--- a/tools/apt-selection
+++ b/tools/apt-selection
@@ -3,7 +3,9 @@
 # This is a little shell script that will launch apt-get in dry-run mode
 # to find all the dependencies of a specific package
 
-set -e
+# There's not set -e here because this script may fail !
+# Apt doesn't always work ... 
+# set -e
 
 # Get the configuration information if necessary
 if [ -z "$TDIR" -o -z "$CODENAME" -o -z "$ARCH" ]; then
