Fix the environment variable checks in tools/generate_di+k_list.

diff --git a/tools/generate_di+k_list b/tools/generate_di+k_list
--- a/tools/generate_di+k_list
+++ b/tools/generate_di+k_list
@@ -3,9 +3,18 @@
 # Generate a list of packages required for debian-installer
 # This script makes use of the following variables that need to be preset:
 # MIRROR, CODENAME, DI_CODENAME
-die "Missing \$MIRROR variable" unless $ENV{MIRROR};
-die "Missing \$CODENAME variable" unless $ENV{CODENAME};
-die "Missing \$DI_CODENAME variable" unless $ENV{DI_CODENAME};
+if [ "$MIRROR"x = ""x ] ; then
+    echo "\$MIRROR unset; abort!"
+    exit 1
+fi
+if [ "$CODENAME"x = ""x ] ; then
+    echo "\$CODENAME unset; abort!"
+    exit 1
+fi
+if [ "$DI_CODENAME"x = ""x ] ; then
+    echo "\$DI_CODENAME unset; abort!"
+    exit 1
+fi
 
 DATE=`date`
 cat > debian-installer+kernel-$DI_CODENAME << EOF
