- Add my exclude_udebs lists, for general and i386, and modify       generate_di_list to not include udebs from those lists onto the       cdrom, to save space on the netinst cds.

diff --git a/tools/generate_di_list b/tools/generate_di_list
--- a/tools/generate_di_list
+++ b/tools/generate_di_list
@@ -1,34 +1,58 @@
-#!/bin/sh
-
+#!/usr/bin/perl -w
 # Generate a list of packages required for debian-installer
 # This script makes use of the following variables that need to be preset:
-# MIRROR, CODENAME
-
-ARCHS="alpha arm hppa hurd-i386 i386 ia64 m68k mips mipsel powerpc s390 sparc sh"
-DATE=`date`
-cat > debian-installer << EOF
-/*  List of udebs to be included so that debian-installer works fine 
+# MIRROR, CODENAME, BASEDIR
+my @ARCHES=qw{alpha arm hppa hurd-i386 i386 ia64 m68k mips mipsel
+              powerpc s390 sparc sh};
+my $DATE=`date`;
+chomp $DATE;
+open(OUT, ">debian-installer") || die "write: $!";
+print OUT << "EOF";
+/* List of udebs to be included so that debian-installer works fine 
  *
  * This list can be generated with the command:
  * ../tools/generate_di_list
  *
  * Last update: $DATE
  */
-
 EOF
 
-for arch in $ARCHS ; do
-  cat >> debian-installer << EOF
-#ifdef ARCH_$arch
-EOF
+my @common_excludes = read_exclude("exclude-udebs");
 
-  grep-dctrl -n -s Package '' \
-  $MIRROR/dists/$CODENAME/main/debian-installer/binary-$arch/Packages \
-  >> debian-installer
+foreach my $arch (@ARCHES) {
+	print OUT "#ifdef ARCH_$arch\n";
+	my @exclude = @common_excludes;
+	push @exclude, read_exclude("exclude-udebs-$arch")
+		if -e exclude_path("exclude-udebs-$arch");
+	my $packagefile="$ENV{MIRROR}/dists/$ENV{CODENAME}/main/debian-installer/binary-$arch/Packages";
+UDEB:	foreach my $udeb (map { chomp; $_ } `grep-dctrl -n -s Package '' $packagefile`) {
+		foreach my $pattern (@exclude) {
+			if ($udeb =~ /^$pattern$/) {
+				next UDEB;
+			}
+		}
+		print OUT "$udeb\n";
+	}
+	print OUT "#endif\n";
+}
 
-  cat >> debian-installer << EOF
-#endif
+sub read_exclude {
+	my $file=exclude_path(shift);
+	open (IN, "<$file") || warn "failed to read exclude file $file";
+	my @ret;
+	while (<IN>) {
+		chomp;
+		s/^#.*//;
+		next unless length;
+		$_=quotemeta($_);
+		$_=~s/\\\*/.*/g;
+		push @ret, $_;
+	}
+	close IN;
+	return @ret;
+}
 
-EOF
-
-done
+sub exclude_path {
+	my $file=shift;
+	return "$ENV{BASEDIR}/data/$ENV{CODENAME}/$file";
+}
