tools/grab_md5: Make arch handling more generic - instead of having to list all arches, allow a wildcard and then check for lack of Packages.gz files

diff --git a/tools/grab_md5 b/tools/grab_md5
--- a/tools/grab_md5
+++ b/tools/grab_md5
@@ -49,10 +49,15 @@ do
                     }
                 }' | sort | uniq >> $OUT
             ;;
-        alpha|amd64|arm|armel|hppa|i386|ia64|m68k|mips|mipsel|powerpc|s390|sparc|kfreebsd-amd64|kfreebsd-i386|hurd-i386)
+        *)
             FILES=`find $LOCATIONS -name Packages.gz | grep binary-$ARCH`
             echo "Using MD5 sums from Packages files:"
             echo $FILES
+            NUM_FILES=`echo $FILES | wc -w`
+            if [ $NUM_FILES -eq 1 ] ; then
+                echo "No files found for arch $ARCH. Abort!"
+                exit 1
+            fi
             zcat -f $FILES | MIRROR=$MIRROR perl -ne '
                 chomp;
                 my $mirror = $ENV{"MIRROR"};
@@ -91,10 +96,6 @@ do
                  fi
             done
             ;;             
-        *)
-            echo "Unknown arch/source $ARCH!"
-            exit 1
-            ;;
     esac
 done
 
