Add initial support for jigdo v2 format
Add the option to switch to format v2 which uses sha256 everywhere
instead of md5. We can't actually turn this on yet, need to wait for
users to upgrade a bit and get new v2-aware jigdo clients.

But this works as-is for generating v1 until we hit that switch - see
the new JIGOO_CHECKSUM option in CONF.sh

diff --git a/tools/grab_checksums b/tools/grab_checksums
--- a/tools/grab_checksums
+++ b/tools/grab_checksums
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# grab_md5
-# (c) 2004-2016 Steve McIntyre <steve@einval.com>
+# grab_checksum
+# (c) 2004-2019 Steve McIntyre <steve@einval.com>
 #
 # GPL v2
 #
@@ -10,11 +10,25 @@
 
 set -e
 
-MIRROR=$1
-ARCHES="$2"
-CODENAME=$3
-DI_CODENAME=$4
-OUT=$5
+CHECKSUM=$1
+MIRROR=$2
+ARCHES="$3"
+CODENAME=$4
+DI_CODENAME=$5
+OUT=$6
+
+case $CHECKSUM in
+    md5|sha256)
+	# OK
+        ;;
+    *)
+	echo "$0: Unsupported checksum specified: $CHECKSUM"
+	echo "Abort"
+	exit 1
+	;;
+esac
+
+export CHECKSUM
 
 for ARCH in $ARCHES
 do
@@ -34,17 +48,23 @@ do
     case $ARCH in
         source)
             FILES=`find $LOCATIONS -name Sources.gz -o -name Sources.xz`
-            echo "Using MD5 sums from Sources files:"
+            echo "Using $CHECKSUM sums from Sources files:"
             echo $FILES
-            $BASEDIR/tools/catz $FILES | MIRROR=$MIRROR perl -ne '
+            $BASEDIR/tools/catz $FILES | \
+		MIRROR=$MIRROR CHECKSUM=$CHECKSUM perl -e '
                 chomp;
                 my %files;
                 my $dir;
-                my $mirror = $ENV{"MIRROR"};
                 my $filename;
+                my $mirror = $ENV{"MIRROR"};
+		my $checksum = $ENV{"CHECKSUM"};
                 while (<>) {
                     if (m/^ ([[:xdigit:]]{32}) (\d+) (\S+)/sg) {
                         $files{$3}{"md5"} = $1;
+                        $files{$3}{"size"} = $2;
+                    }
+                    if (m/^ ([[:xdigit:]]{64}) (\d+) (\S+)/sg) {
+                        $files{$3}{"sha256"} = $1;
                         $files{$3}{"size"} = $2;
                     }
                     if (m/^Directory: (\S+)/sg) {
@@ -53,7 +73,7 @@ do
                     if (m/^$/) {
                         for $filename (keys %files) {
                             printf("%s  %12s  %s/%s/%s\n",
-                                $files{$filename}{"md5"},
+                                $files{$filename}{$checksum},
                                 $files{$filename}{"size"},
                                 $mirror, $dir, $filename);
                         }
@@ -64,19 +84,21 @@ do
         *)
             FILES=`find $LOCATIONS -name Packages.gz \
                    -o -name Packages.xz | grep binary-$ARCH`
-            echo "Using MD5 sums from Packages files:"
+            echo "Using $CHECKSUM sums from Packages files:"
             echo $FILES
             NUM_FILES=`echo $FILES| wc -w`
             if [ $NUM_FILES -eq 1 ] ; then
                 echo "No files found for arch $ARCH. Abort!"
                 exit 1
             fi
-            $BASEDIR/tools/catz $FILES | MIRROR=$MIRROR perl -ne '
+            $BASEDIR/tools/catz $FILES | \
+		MIRROR=$MIRROR CHECKSUM=$CHECKSUM perl -e '
                 chomp;
                 my $mirror = $ENV{"MIRROR"};
+		my $checksum = $ENV{"CHECKSUM"};
                 my $filename;
                 my $size;
-                my $md5;
+                my $sum;
                 while (<>) {
                     if (m/^Filename: (\S+)/sg) {
                         $filename = $1;
@@ -84,11 +106,14 @@ do
                     if (m/^Size: (\S+)/sg) {
                         $size = $1;
                     }
-                    if (m/^MD5sum: (\S+)/sg) {
-                        $md5 = $1;
+		    if ($checksum eq "md5" and (m/^MD5sum: (\S+)/sg)) {
+                        $sum = $1;
+                    } elsif ($checksum eq "sha256" and (m/^SHA256: (\S+)/sg)) {
+                        $sum = $1;
                     }
                     if (m/^$/) {
-                        printf("%s  %12s  %s/%s\n", $md5, $size, $mirror, $filename);
+                        printf("%s  %12s  %s/%s\n", $sum, $size, $mirror, $filename);
+			$sum = "";
                     }
                 }' | sort | uniq >> $OUT
             # Use the new D-I images. Do NOT use the "current"
@@ -96,15 +121,19 @@ do
             for VER in $MIRROR/dists/$DI_CODENAME/main/installer-$ARCH/*
             do
                 if [ -d $VER ] && [ ! -L $VER ] ; then
-                    FILE=$VER/images/MD5SUMS
-                    echo "Using MD5 sums from d-i: $FILE"
+		    if [ $CHECKSUM = md5 ]; then
+			FILE=$VER/images/MD5SUMS
+		    else
+			FILE=$VER/images/SHA256SUMS
+		    fi
+                    echo "Using $CHECKSUM sums from d-i: $FILE"
                     LOC=dists/$DI_CODENAME/main/installer-$ARCH/`basename $VER`/images
                     for ENTRY in `cat $FILE | sed 's/  /:/g'`
                     do
                         PATH=`echo $ENTRY | /bin/sed "s?^.*:\./?$MIRROR/$LOC/?g"`
-                        MD5=`echo $ENTRY | /bin/sed 's/:.*$//g'`
+                        CSUM=`echo $ENTRY | /bin/sed 's/:.*$//g'`
                         SIZE=`/usr/bin/stat -c %s $PATH`
-                        printf '%s  %12.12s  %s\n' $MD5 $SIZE $PATH
+                        printf '%s  %12.12s  %s\n' $CSUM $SIZE $PATH
                     done | sort | uniq >> $OUT
                  fi
             done
@@ -113,3 +142,4 @@ do
 done
 
 exit 0
+
